spring:
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0 # 指定redis的分库（共16个0到15）

#OpenAI 配置
OpenAI:
  apikey: ${OPENAI_API_KEY} #your openai-apikey in system

#向量数据库
milvus:
  host: 127.0.0.1
  port: 19530
  collectionName: note